apiVersion: kaptain.org/1.16
kind: docker-build-dockerfile
metadata:
  description: "Python 3.10 environment base image"

spec:
  layers:
    - ghcr.io/kube-kaptain/layerset/layerset-image-environment-base:1.3
