name: Dockerfile Build

on:
  push:
    branches: ['main*']
  pull_request:
    branches: ['main*']

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.1.21
    permissions:
      contents: write
      packages: write
      checks: write

